karthink/gptel

gptel-curl.el
gptel.el

In order to use this your authinfo.gpg file should contain an entry like this:
~~~
machine openai.com login apikey password <key>
~~~

Add gptel-api-key-from-auth-source (Fix #13)

---

gptel-transient.el
gptel.el

Based on the new model update that got announced recently:
Not sure how welcome this is, might get a bit tricky to keep up to date.

Add new turbo 0613 models

---

gptel-transient.el

https://github.com/karthink/gptel/issues/95

Exit gptel-system-prompt after selected

---

README.org

Perplexity.ai provides an OpenAI-style API.
This PR also removes some extra whitespace.

README.org: Update with instructions for perplexity.ai

---

gptel-gemini.el

gptel-gemini.el: There may soon be more than one Gemini model. This PR changes how the URL is built to support future additional model options.

:recycle:: Untangle Gemini model and endpoint

---

gptel-transient.el

I just noticed the prompt saying "You are a python-ts programmer." :)

gptel-transient: Also remove "-ts" suffix from major mode

---

gptel.el

- OpenAI released new "GPT 4 Turbo"
- https://platform.openai.com/docs/models/continuous-model-upgrades

Add GPT 4 Turbo

---

gptel-anthropic.el

This model was recently released by Anthropic, and is now Anthropic's strongest model.
See https://docs.anthropic.com/en/docs/about-claude/models

Add `claude-3-5-sonnet-20240620` to gptel-anthropic.el

---

README.org

News about the 3.1 models: 
- https://llama.meta.com/
- https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/
Groq related docs: https://console.groq.com/docs/models

README: Update Groq default models

---

README.org
gptel.el

> Try, test, and deploy from a wide range of model types, sizes, and specializations.
Besides supporting the Azure SDK, Github Models also supports OpenAI. I tried the [same setup](https://github.com/karthink/gptel/discussions/385#discussioncomment-10664014) with `gptel-make-azure` but had no success.

Add Github Models

---

README.org

consult-web is now deprecated in favor of [consult-omni](https://github.com/armindarvish/consult-omni).

README: Update reference to consult-web

---

.github/ISSUE_TEMPLATE/bug_report.md

github: Add bug report template

meta: Add bug report template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support-request.md

github: Add support request template

meta: Add support request template

---

.github/ISSUE_TEMPLATE/enhancement-or-feature-request.md

github: Add feature request template

meta: Add feature request template

---

README.org

It took me too long to search for this. It deserves an explicit callout like this IMHO.
Great mode, BTW!  This is amazing!

Added a section tell new users how to select a backend explicitly

---

README.org

README: add prefix string docs for gptel-org-branching-context

---

README.org

Package is now read-only and not maintained.

Remove gptel-extensions package

---

gptel-openai.el

chore: update gptel-openai.el

---

gptel-privategpt.el

followup to https://github.com/karthink/gptel/commit/0a2c07a2a41e5d96e8886fd7e761eefe55caa647 for privategpt

fix(private-gpt): passing system directive

---

gptel-transient.el

* gptel-transient.el (gptel--crowdsourced-prompts): Improve parsing by supporting CSV fields that are not quoted.
This should fix #614

gptel-transient: Improve parsing of crowdsourced prompts CSV file

---

README.org
gptel.el

Just a bunch of minor tweaks to documentation. Also added two new keywords "llm" and "ai".

Small documentation tweaks

---

gptel-transient.el

* gptel-transient.el (gptel--transient-read-variable, gptel--transient-read-number): New function that uses standard `read-number' to read a numeric value, returning nil for default.  Drop the read-variable function since we were only using it for prompting numbers.
* gptel-transdient.el (gtpel--infix-num-messages-to-send, gptel--infix-max-tokens, gptel--infix-temperature): Use the new function as :reader.
This also fixes handling of history, which is broken with at least transient 0.8.4.

gptel-transient: Ensure user enters a number when prompted

---

gptel.el

* gptel.el (gptel--openai-models): Add gpt-4.5-preview.
See https://openai.com/index/introducing-gpt-4-5/

Add support for gpt-4.5-preview

---

.elpaignore

I guess there is no change too small not to introduce a typo, sorry.

elpaignore: Oopsie daisy

---

gptel-ollama.el

* gptel-ollama.el (gptel--request-data): Replace "ChatGPT" with "Ollama" in docstring for ollama method.

gptel-ollama: Fix docstring

---

gptel.el

Hello,
A simple change to add OCaml to the list of inferred programming languages

gptel--mode-description-alist: add OCaml

---

README.org

'gemini-pro model has been removed, update README to not confuse new user

[README] provide update-to-date Gemini setting

---

NEWS
gptel-gemini.el

This PR adds Gemini 2.5 Flash Preview: https://ai.google.dev/gemini-api/docs/models#gemini-2.5-flash-preview

Add `gemini-2.5-flash-preview-04-17` model to `gptel-gemini.el`

---

README.org

Documentation of Sambanova in README.org as you suggested in https://github.com/karthink/gptel/issues/684

Readme: added sambanova documentation

---

gptel-gemini.el

As noted in various places, including [LangChain](https://github.com/langchain-ai/langchainjs/pull/5247), Gemini's support for JSON Schema is incomplete. The `additionalProperties` field and the `format` property on `string` types are not supported.
This filters them out of Gemini API tool calls, so that tools that define these properties (e.g. from MCP servers) don't immediately cause a 400 when invoking Gemini.

fix: Filter unsupported JSON Schema attributes out of Gemini tool calls

---

gptel-gemini.el

Previous implementation (#827) didn't recurse correctly into nested sub-schemas -- this does a better job.

gptel-gemini: Fix filtering of unsupported attributes in tool calls

---

gptel.el

Fix issue:
```
Debugger entered--Lisp error: (wrong-number-of-arguments setq 1)
(setq arg-values)
(let (args name arg-values tool-spec process-tool-result) (setq args (plist-get tool-call :args)) (setq name (plist-get tool-call :name)) (setq arg-values) (setq tool-spec (cl-find-if #'(lambda (ts) (equal (progn (or ... ...) (aref ts 2)) name)) (plist-get info :tools))) (setq process-tool-result #'(lambda (result) (plist-put info :tool-success t) (let ((result (gptel--to-string result))) (plist-put tool-call :result result) (setq result-alist (cons (list tool-spec args result) result-alist))) (setq tool-idx (1+ tool-idx)) (if (>= tool-idx ntools) (progn (gptel--inject-prompt backend (plist-get info :data) (gptel--parse-tool-results backend ...)) (funcall (plist-get info :callback) (cons ... …
```

fix: arg-values default value

---

gptel-curl.el
gptel-openai.el
gptel.el

GPTEL-only changes for bedrock.
(follow-up from #867 )

GPTEL changes for bedrock

---

gptel-bedrock.el

Adding Claude 3.7 Sonnet  to the list of model IDs.

Add Claude 3.7 Sonnet model ID

---

gptel-gemini.el

Also introduce 2.5-flash-lite.

Add gemini-2.5 pro and flash productin models

---

gptel-openai.el

Be more resilient against chunked tool_calls in gptel-openai.el

---

gptel-gh.el

Update model list for github copilot to include gpt-5

gptel-gh: update model list

---

NEWS
gptel-gh.el

Add support for `claude-sonnet-4.5` and `gpt-5-codex`

gptel--gh-models: add new models
