gptel.el

Hello,
I use `gptel-send` command more frequently than `gptel`. It would be nicer if this command were autoloaded.

Add autoload for gptel-send

---

gptel.el

These two commits fix handling of multi-byte characters in the prompt send to OpenAI and in the response received from it.
As a result, you can now use non-Latin alphabets like Greek, or emojis.
To make requests work, it was necessary to encode the loaded API key as utf-8, for reasons that remain obscure, but may have to do with some subtlety concerning how the `concat` function combines multibyte and non-multibyte strings. To make replies work, it was necessary to decode the response body as utf-8 before, not after, parsing it as json.
I have tested this lightly on Emacs 28.1 running on Linux.

Resolved #4: Handles multi-byte characters with url-retrieve (i.e., without the external curl command)

---

README.org

* README.org Update the instructions for getting =gptel-api-key= to include using the .authinfo file after support was added in 6f951ed.

README: Update instructions for setting key

---

README.org
gptel-curl.el
gptel.el

This is a similar PR to https://github.com/karthink/gptel/pull/49. I submitted a new PR because:
1. @christianromney has not replied for a month
2. The API key may also be related to the host for some API proxy services like https://aiproxy.io
3. Most API proxies use the same `basePath` & `Path` as the OpenAI API, i.e. "/v1/chat/completions", so we only need to make the Host configurable.

Make API host configurable

---

gptel.el

To read from .authinfo.gpg the key parameter :require for auth-source-search is needed.

Update gptel.el: Needs :require for auth-source-search

---

gptel.el

not sure if this was a deliberate choice but I assumed it wasn't, I was playing around with gtpel-request and wanted to use the builtin prompt functionality but with a custom system message

add optional system message argument to gptel--create-prompt

---

gptel-transient.el
gptel.el

The returned result now is a string instead of a number, and the code is from `set-variable`.

Fix read temperature from minibuffer

---

gptel-curl.el

Often local LLMs will offload a query to CPU if there is not enough VRAM or in
the case of an unsupported GPU. When a query is offloaded to the CPU responses
can be significantly slower. If curl times out early the user will not get the
response from the LLM back in Emacs.
This change increases the timeout for curl from 60s to 300s to make gptel usable
in slower environments.
Closes #125

Increased curl timeout

---

README.org

1. According to Azure OpenAI [documents](https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line%2Cpython&pivots=rest-api), the chat API endpoint should be "/openai/deployments/gpt-4/chat/completions?api-version=2023-05-15" and the one show in README is the [completion API](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line%2Cpython&pivots=rest-api) without "chat".
2. Azure OpenAI also requires an API key.
This PR is related to https://github.com/karthink/gptel/issues/143.

update the instruction for Azure

---

gptel-curl.el
gptel.el

Firstly, I'd like to express my gratitude for the excellent `gptel` package.
Recently, with the release of newer models boasting a 128k context (e.g., `gpt-4-1106-preview`), I attempted to utilize these capabilities with a sizable amount of data. However, I encountered a stumbling block when `gptel-stream-response` failed due to a Curl error stating that the "argument list [was] too long."
Upon investigation, I found that the issue arose from attempting to pass a large payload directly to Curl via command-line arguments. To overcome this limitation, I have implemented a solution that writes the JSON-encoded data to a temporary file and instructs Curl to transmit this data using the `--data-binary` flag, which points to the said file. This eliminates the problem of exceeding the maximum …

Fix for "argument list too long" error with large payloads in Curl

---

gptel-curl.el
gptel-ollama.el
gptel-openai.el
gptel.el

This makes it so that prefixes with newlines are respected s.t. the point is moved to the end of the prefix:
Before, the point would be at the end of the first line. This saves two key presses.

Add multiline prefixes & AI response prefixes

---

README.org
gptel-curl.el
gptel-transient.el
gptel.el

This PR proposes a customisable option `gptel-update-destination` to enable status messages to appear strictly in the minibuffer and never appear in the header line.

Add custom gptel-update-destination

---

gptel-curl.el
gptel-gemini.el
gptel-kagi.el
gptel-ollama.el
gptel-openai.el

This slot is used to append backend specific options to the curl arguments used to make HTTP requests. The backend specific arguments are appended after `gptel-curl--common-args`.
My use case for this feature is to set the `--cert` and `--key` options in a custom backend that uses mutal TLS to communicate with an OpenAI proxy/gateway.

Add curl-args slot to gptel-backend

---

gptel-transient.el

At the moment, the transient can assign `h` to one of your directives and then you need to use the mouse to customize directives on the fly. Also, if all characters of your directive name were already assigned, it would not assign any. With this PR, an arbitrary unused key will be assigned instead.

Avoid clashes with the custom directive key and use an arbitrary unused key in the worst case

---

README.org

Add a reference to [magit-gptcommit](https://github.com/douo/magit-gptcommit) in the README's extensions section. magit-gptcommit is a package that depends on GPTel to generate Git commit messages within the magit-status buffer.

README: New pacakge based on gptel, magit-gptcommit

---

gptel-gemini.el

Gemini 1.5 is now in [general availability](https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html).
Closes #212.

:sparkles:: Add Gemini 1.5

---

gptel.el

OpenAI has released a new model called GPT-4o, or "GPT-4 Omni". More information [here](https://openai.com/index/hello-gpt-4o/).

Add new model: GPT-4o

---

gptel.el

This commit modifies the behavior of the gptel function so that, in the case where the function is called interactively, and multiple gptel sessions already exist (as judged by there being multiple buffers with the minor mode gptel-mode enabled), then the function prompts the user to select one of those buffers.
This replaces the previous behavior in this case, which was just to switch to the buffer named `backend-name` if it already existed, or else to create a new buffer with that name.
So, after this comit, the gptel function behaves as follows:
- (NEW). When called interactively and multiple gptel-mode buffers exists, it prompts the user to choose a buffer to switch to.
- when called interactively and no gptel-mode buffers exist, it creates a buffer named `backend-name`
- when called …

gptel asks user to select a buffer if many are open

---

README.org
gptel-privategpt.el

Hi, as suggested in our recent discussion #305, here's a PR that adds support for interacting with privateGPT. Its based on the openai-backend, with some additions. The focus was to enable the use of two specific key words, as described in the [API reference](https://docs.privategpt.dev/api-reference/api-reference/contextual-completions/chat-completion-v-1-chat-completions-post-stream):
1) `use_context`: directs the LLM to use the context of documents that have been "ingested"
2) `include_sources`: directs the LLM to also return information about the sources of the context (so far: file name and page number, if appropriate).
I changed the code of `gptel-openai.el`to send the additional keywords to the llm server, and to correctly parse the answer if sources are provided. 
I tested the …

Support for privateGPT, including support for RAG functions like rspecting context and parsing of sources

---

gptel-transient.el

ChatGPT response contains three backticks with programming language name at the first and last lines which prevents ediff from working properly.
Fixes #344

Clean up response before ediffing

---

gptel-context.el

When gptel-context-add was called with a positive prefix argument to select a buffer to add to the context, it was using `point-min` and `point-max` of the _current buffer_ to determine the region of context, instead of the target buffer. This meant the context didn't contain the whole target buffer. The fix is straightforward: just make sure to use the target buffer's `point-min` and `point-max` instead.

Fix gptel-context-add handling of region boundary when choosing a buffer

---

gptel-transient.el

This change I believe is more useful for a typical user in the following common use case
I as a user would like not to refactor but to rewrite in a specific way mentioning what is important. With the existing default prompt I need to formulate it like "Refactor/rewrite in a way that {details}" repeating "Refactor" twice in different places. With "Refactor the following code." being a suffix, I just need to press Backspace once removing dot and start typing {details} right away.
"Generate only code, no explanation" chunk is a part that rarely gets updated so it might be better to keep it in the middle because users won't need to access it often.

Change order of Refactor sentences in gptel--rewrite-message

---

README.org
gptel.el

Adding Cerebras section to the README as api.cerebras.ai supports and Open AI interface

Adding Cerebras support

---

test/gptel-org-test.el

* 3e50928 2024-refactor-tests origin/2024-refactor-tests chore(test/gptel-org-test): turn off byte-compiling for tests
* 937c3a0 fix(test/gptel-org-test): explicitly require needed gptel-org

[tests] Refactor tests (explicit require, no byte-compile)

---

README.org

Spacemacs has an `llm-client` layer that supports `gptel`. This layer also resolves (in Spacemacs) GH-237 by disabling purpose mode for `gptel`, providing a working out-of-the-box experience for Spacemacs users.

Update Spacemacs installation instructions

---

gptel.el

I understand that `gptel-model` takes a symbol rather than a string now, so I believe the docstring should be updated to reflect this change.

Update `gptel-model` docstring

---

README.org

Since I have archived the chatgpt-arcana repo in favour of this one, there's no need to link to it!

Remove chatgpt-arcana from the list of alternatives

---

gptel-anthropic.el

- Add `claude-3-5-sonnet-20241022`, the upgraded Claude 3.5 Sonnet model
released on 2024-10-22. “The upgraded Claude 3.5 Sonnet delivers
across-the-board improvements over its predecessor, with particularly
significant gains in coding—an area where it already led the field.”
(https://www.anthropic.com/news/3-5-models-and-computer-use)
- Replace a source with a more comprehensive one.

gptel-anthropic: Add upgraded Claude 3.5 Sonnet model

---

README.org

Add new LLM provider: Novita AI

docs: add Novita AI in README

---

gptel-curl.el

We use curl's header size output to `goto-char` to the end of the response header (to parse the JSON that starts there).
On Windows, however, processes we launch will typically output Windows-style line endings, with CR-LF; by default, Emacs tries to convert this to just CR, to avoid seeing ugly `^M` characters at the end of lines.
`curl` dumps what it gets from the server directly... but HTTP also specifies
CR-LF line endings, at least at the end of headers. On Windows, Emacs converts
these to CRs, removing the LFs, and thus causing our header size measurement to
be slightly off (the buffer now includes fewer characters of header vs. what
`curl` told us we'd have). So `goto-char` seeks too much ahead, missing the
beginning of the JSON; we get a JSON parse error.
This PR fixes this by …

gptel-curl: don't try converting CR-LF on Windows

---

README.org

README: Add support for xAI

---

gptel-privategpt.el

the switch to symbol for models means we need to convert them back to strings in json requests.

fix(private-gpt): convert model name from symbol to string in request

---

gptel-transient.el

Before this, inspecting your query causes the status message to get stuck on "Waiting..."

Fix bug where dry run updates status message

---

gptel-ollama.el

See #473.
This simplifies `gptel--request-data`, ensuring that model or backend-specific parameters are preserved without overriding the global options

Possible bug fix 473

---

README.org
gptel-context.el

Currently, attempting to add directories to the context in Dired will throw an error. This PR provides support for adding files in directories to the context: if there is a directory at point, or the marked files include one or more directories, their files will recursively be added to the context.

Support adding files in directories to context

---

gptel.el

This makes sure that windows doesn't bark at you when you pass arguments to the curl subprocess over window's limit of 32767.
closes #517

Add windows platform check for the curl file size thresh

---

gptel-gemini.el

Information about this model from the Go SDK for Generative AI:
name: gemini-2.0-flash-thinking-exp
Description: Gemini 2.0 Flash Thinking Experimental
Max tokens: 32767
Additional information from their website:
Thinking Mode is an experimental model and has the following limitations:
32k token input limit
Text and image input only
8k token output limit
Text only output
No built-in tool usage like Search or code execution
As of Dec, 2024, Google says the knowledge cutoff for Gemini-2.0-flash-exp is "August 2024".

Add gemini-2.0-flash-thinking-exp

---

gptel-openai.el
gptel.el

o1 has superceded o1-preview, the costs are the same, o1 is either identical or better than o1-preview

Add support for OpenAI o1 model

---

gptel-rewrite.el

Steps to reproduce: using gptel-rewrite with mark-even-if-inactive set
to nil (and tmm enabled) yields the error "The mark is not active now".
* gptel-rewrite.el (gptel--suffix-rewrite): Postpone deactivate-mark
to prevent "The mark is not active now" error when
`mark-even-if-inactive' is nil.

Fix mark deactivation timing in gptel-rewrite

---

gptel-context.el

I'm not sure how I closed #478 or why this new commit didn't appear back in that pull request. Either way, here it is again without the formatting changes!

gptel: Use substitute-command-keys in context

---

gptel.el

When the tool call succeeds (as in does not error) but returns nil, we still need to show the model that the tool returned a nil result.
Otherwise the model seems to not progress in its reply.
`gptel--to-string` handles this fine and the model happily reported observing the "nil" result.

Pass nil results through to model

---

gptel.el

```
:TOOL_CALL:
(all_arg_types (:foo 42))
object: (:foo 42)
```
:boom: 
:shipit: 
Related tool example found [here](https://github.com/karthink/gptel/issues/514#issuecomment-2627491244)
I found this by inspecting the tool use and noticing a `:parameters nil` in the plist describing the tool to the backend.  The object spec wasn't being given to the backend at all.

Parameters Required

---

gptel-curl.el
gptel.el

With fancy graphical headings, empty lines are unneeded and actually quite bad.
I can't imagine anyone wants values other than 1 or 2.  Maybe this should be...
`gptel-response-blank-line'?
I can rework it.  Probably the right way to decide is "what will users recognize on first glance?"

Variable number of newlines before responses

---

README.org
gptel-org.el

[This explains](https://github.com/karthink/gptel/issues/294) that gptel needs Org version 9.7+ so this patch updates the notice for the user.

Updates required Org version notice from 9.6.7 to 9.7

---

gptel-context.el

Use the current buffer as the default choice when using `-b` in the GPTel transient.

gptel-context: Use current buffer as default

---

gptel-org.el

- Added checks to ensure paragraph (`par`) is valid before accessing its
- properties.  Safeguarded against `nil` values for `:contents-begin`
- and `:contents-end` properties.  Ensured the function proceeds only if
- all necessary properties are non-nil.
These changes prevent errors when element properties are unexpectedly `nil`, like when trying to send this, with one or more characters between the brackets
\#+begin_src
[[ ]]
\#+end_src
closes https://github.com/karthink/gptel/issues/593

Improve robustness: `gptel-org--link-standalone-p`

---

gptel.el

* gptel.el (gptel-model): Ensure the docstring documentation and customization options are current (in sync with
`gptel--openai-models') by dynamically generating them instead of hard-coding.

gptel: Make gptel-model variable definition dynamic

---

gptel-transient.el

I find no value in activating the directive in the edit buffer as region, and it can be quite annoying.
Additionally, since the directives and system messages are primarily regular text, enabling visual-line-mode (word wrapping) seems logical.

gptel-transient: Improve directive/system message editing

---

gptel-rewrite.el
gptel-transient.el

* gptel-transient.el (gptel--read-crowdsourced-prompt, gptel--edit-directive, gptel--suffix-system-message): Deactivate the mark after entering the prompt-edit buffer for a crowdsourced prompt (#616). This behaviour was introduced in commit cc53a81c, but it did not actually work since `deactivate-mark' was called after returning from `gptel--read-crowdsourced-prompt', when it was too late.
(Also a slight indentation adjusment, @karthink are you editing elisp with some non-standard indentation mode?)

gptel-transient: (really) unmark before editing crowdsourced prompt

---

gptel-transient.el

* gptel-transient.el (gptel--edit-directive): `make-separator-line' is a function introduced in Emacs 28.1, so it was disabled with a comment.  However, we require compat-29.1.4.1 making the function available in Emacs ~~28~~ EDIT: 27, and it is already used in other places, so enable it here as well.  Drop the extra newline from the examples above.

Fix read-only behaviour in gptel--edit-directive

---

README.org

The extra quote was causing an error of `encode-coding-string: Wrong type argument: json-value-p, string`.

Fix type error in read_buffer tool use example

---

gptel-gemini.el

See #634, suggestion by @metachip.
Adds
- `gemini-2.0-flash`
- `gemini-2.0-flash-exp`
- `gemini-2.0-flash-lite-preview-02-05`
- `gemini-2.0-flash-thinking-exp-01-21`
- `gemini-2.0-pro-exp-02-05`
Removes
- `gemini-2.0-flash-thinking-exp` (superseded by `gemini-2.0-flash-thinking-exp-01-21`)

Update gptel-gemini.el models

---

gptel-transient.el

* gptel-transient (gptel-menu): Fix a slight bug introduced in commit edf834a ("Provide description of send action") where an extra quote (') caused error "Invalid face reference: quote" to appear in *Messages* and the "Context" heading to have incorrect face (color).

gptel-transient: Fix face related bug

---

gptel-transient.el

* gptel-transient.el (gptel-option-overlaid): Use a proper ellipsis (…) instead of three ASCII dots (...) when truncating the user instruction, provided Unicode is displayable and `truncate-string-ellipsis' is nil.  This change allows for two additional characters and enhances visual appeal and consistency.

gptel-transient: Use proper ellipsis for consistent UI

---

gptel-transient.el

* gptel-transient.el (gptel--describe-suffix-send): Enhance reporting to include the line count of the most recent kill from the kill ring, or indicate "empty" if the kill ring is devoid of entries.

gptel-transient: Report what is being sent from kill-ring

---

gptel-openai-extras.el

Add the following Perplexity models (https://docs.perplexity.ai/guides/model-cards)
- sonar-reasoning
- sonar-reasoning-pro
- sonar-deep-research

gptel-openai-extras: reasoning and deep-research perplexity models

---

README.org
gptel-transient.el
gptel.el

GPT, or Generative Pre-trained Transformer, is a designation originally used by OpenAI to describe their language models. Other companies or researchers might develop models with similar architectures, but "GPT" primarily associates with OpenAI's series.
* gptel.el (gptel-model, gptel-mode): Use "LLM model" instead of "GPT model".
* README.md: Ditto.
* gptel-transient.el (gptel--infix-provider): Just "Model" instead of "GPT Model".  The meaning should be clear in this context, and leaves bit more space for potentially long model names.

gptel: Prefer LLM terminology over GPT

---

README.org
gptel-anthropic.el
gptel-curl.el
gptel-gemini.el
gptel-kagi.el
gptel-ollama.el
gptel-openai-extras.el
gptel-openai.el
gptel-org.el
gptel-rewrite.el
gptel-transient.el
gptel.el

**Draft**
And does not pass tests yet.  Should be close to passing.  Just sleepy and wanted to give PST a chance to take a look at approaches before I finish up.
One of my commits almost vanished during merge and became whitespace only.

Explicit Tool Turns

---

README.org

Fixed a small typo I discovered while playing with tools

Fix typo in docs

---

NEWS

Use `#' instead of Lisp `;;;' for comment.  This way Github hides it, and it's more correct.
(_Bikeshedding:_ Or should we use `NEWS.org` instead, to be consistent with `README.org`? Also many projects like `transient.el` use `CHANGELOG`.)

NEWS: Use org comment

---

gptel.el

**Description:**  
Previously, the "o3-mini" model stopped accepting system prompts, leading to the introduction of the `nosystem` capability in gptel. However, OpenAI once again allows system prompts (with function equivalently to "developer messages") allowing to restore Markdown formatting by including "Formatting re-enabled" at the start of the system prompt.
Removing the `nosystem` capability from “o3-mini” allows gptel to once again send system prompts, and in turn re-enable Markdown output for users who prepend instructions like “Formatting re-enabled” to their prompts.
**Changes**  
- Remove/comment out the `nosystem` capability for “o3-mini.”  
- Allow system prompts (e.g., “Formatting re-enabled”) to restore Markdown formatting in responses.
**Testing**  
Verified locally by …

Enable Markdown formatting for "o3-mini" by removing `nosystem` capability

---

README.org

Drop leafy-mode, it's gone 404 from Github.  Add Minuet, which is a new code-completion specific LLM client.

README: Tweak list of alternatives

---

gptel-org.el
gptel.el

* gptel.el (gptel--restore-props): Save `buffer-modified-p` before restoring properties and revert it to its original state.  This prevents a visited file from being marked as modified until the user actually makes changes.  This is particularly useful when multiple files are accessed automatically, such as from the `org-agenda-files` location (otherwise when exiting Emacs the user is asked about each file if it needs to be saved).
* gptel-org.el (gptel-org--restore-state): Likewise for Org.

gptel: Ensure restoring state does not flag the buffer modified

---

README.org

Reading #275, I noticed that there was some confusion around how to use `gptel-api-key` and if you had to provide your own function for reading the keys out of `auth-sources`. I thought I'd take a shot at updating the documentation to make it a bit clearer on how this works.

README: Clarify backend configuration and registration

---

README.org

* README.org: Move authinfo explanation to a new section, and make it clear that it's optional.  This builds on #715.

README: Restructure authinfo explanation

---

gptel-rewrite.el

* gptel-rewrite.el (gptel--rewrite-diff): Show the difference between buffers rather than file names.  Otherwise, if a) the buffer has never been saved, the error "No such file or directory" will occur, or b) if there are unsaved changes in the buffer, the diff output will not reflect those changes.

gptel-rewrite: Diff buffers, not files

---

gptel-rewrite.el

* gptel-rewrite.el (gptel--rewrite-dispatch): The function `rmc--add-key-description` was introduced in Emacs 29, resulting in an error for `gptel-rewrite`: "mapcar: Symbol’s function definition is void: rmc--add-key-description".  For older supported Emacs versions, skip this part to restore rewrite functionality, albeit with slightly reduced user guidance.  The actual rmc menu remains accessible in the minibuffer.

gptel-rewrite: Make rewrite work on Emacs < 29 again

---

gptel-rewrite.el

I think this is a reasonable workaround for #730.

gptel-rewrite: Ensure kill-buffer does not ask for confirmation

---

README.org

With default Emacs configuration, latest stable (tagged) version of gptel is available for installation from NonGNU ELPA, so it is not the latest commit that will be installed if the user has not modified `package-archives`.
README.org: Make it more clear how to install stable or latest commit, and mention `use-package`.

README: Clarify installation instructions

---

gptel-anthropic.el

I believe this fixes https://github.com/karthink/gptel/issues/725
When a `message_delta` event is received, we append any tool calls from the response to the global vector of messages and then modify the `tool-use` lists in the FSM info to put them in the right shape for actually invoking tools. This can cause issues if an error occurs after those modifications have already been made - if the `gptel--json-read` call for the `message_delta`'s data fails because we don't yet have the full object, the error handler silently discards the error and resets the point to the start of the same event again. Next time we re-enter `gptel-curl--parse-stream`, we'll again try to process the `message_delta` event but because we modified the tool use blocks in the last invocation, we'll push duplicate …

prevent invalid duplication of tool_call messages

---

gptel-gemini.el

This PR adds recently released `Gemini 2.5 Pro Experimental 03-25`: https://ai.google.dev/gemini-api/docs/models#gemini-2.5-pro-exp-03-25

Add `gemini-2.5-pro-exp-03-25` to `gptel-gemini.el`

---

gptel-rewrite.el

Avoid these warnings:
Warning: Missing format argument in 'with-demoted-errors`
This was also suggested by Stefan Monnier in the emacs-devel mailing list.

gptel-rewrite: Use correct form of `with-demoted-errors`

---

gptel.el

Currently, something like this simply terminates when the LLM tries to invoke a tool:
```elisp
;; Tools disabled by default.
(setq gptel-use-tools nil)
(setq gptel-tools my-tools)
;; Enable tools for a specific request.
(let ((gptel-use-tools t))
(gptel-request "Do something with the tools"))
```
The proposed changes allow the LLM to use tools based on the request-time value of `gptel-use-tools`, rather than its value when the actual tool use is attempted.
Note: this slightly changes the existing behavior in the (unexpected) edge case where `gptel-use-tools` is globally non-nil and `gptel-tools` is nil at request time, but the LLM tries to use a tool anyway. In that case, these functions now return nil (because `:tools` never gets set on the context object) and the request simply …

Allow tool use if `gptel-use-tools` was non-nil at request time

---

gptel-curl.el
gptel.el

Bullet points (•) from GPT responses get incorrectly printed as `â\200¢` in the `*ChatGPT*` buffer.
The problem does not seem to happen if the process coding system is explicitly set to `utf-8-unix` when reading output from subprocesses.
Platform: Linux (Debian 12.5)
(I have been using gptel since around two weeks and it is great! Thank you karthink.)
Below is a screenshot of the incorrect printing of bullets:
Below is a screenshot after this code commit.

UTF-8 encoding issue in *ChatGPT* buffer

---

gptel-rewrite.el

When rewriting sections of Lisp or other code where the initial character is a parenthesis, it results in `show-paren-mode`highlighting the entire overlay when the point is positioned within the overlay area.  Avoid this issue by using a higher priority for `gptel-rewrite-highlight-face`.  (#691)
* gptel-rewrite.el (gptel-rewrite-highlight-face): Inherit from the `default'`face to avoid foreground being the same as `show-paren-match`, which is usually a reverse color. (gptel--rewrite-callback): Use priority higher than `show-paren-priority`.
---
I believe this fixes issue #691.

gptel-rewrite: Make other modes not clobber rewrite overlay

---

gptel.el

Usually I set the temperature to nil to allow the backend to use its default temp, but I noticed customize-variable doesn't provide that as an option, and setopt complains about nil not being a number.

allow customize-variable to set temperature to nil

---

gptel-gh.el

This adds the gemini 2.5 pro model to the github copilot chat backend as well
Signed-off-by: Tianrui Wei <tianrui@tianruiwei.com>

chore: add gemini 2.5 pro model for gh copilot chat

---

README.org

It looks like there was a mismatched copy/paste in #767 which caused the entire "Usage" section of the README to be hidden by default in GitHub's viewer (revealed only by expanding the Copilot Chat instructions). This is just a change to close the tag as needed and bring back the missing section.
Before:
After:

Fix pairing of details tags

---

README.org
gptel-openai-extras.el

Note: xAI has an image generation model, but it's served from a different endpoint, and I'm not sure how well it work with GPTel. I also opted to choose the "latest" variants for these models based off of the description on the model page:
[xAI Model Overview](https://docs.x.ai/docs/models)

docs: update xAI backend with Grok 3 model variants

---

gptel-gemini.el

This PR provides support for the Gemini 2.5 Pro Preview model. This models differs from Gemini 2.5 Pro Exp in that (1) it is paid rather than free and (2) it is not rate-limited to 5 requests per minute and 25 requests per day.

gptel-gemini: Add support for Gemini 2.5 Pro Preview

---

.dir-locals.el

.dir-locals.el: Set `indent-tabs-mode` to nil to avoid whitespace problems (particularly with `aggressive-indent-mode`), as the project predominantly uses spaces for indentation.  Ensure sentences end with double spaces to adhere to the house style.  Point `bug-reference-url-format` to Github issues; while there are few bug references in the codebase, this may be useful later.

dir-locals: Set some project specific local variables

---

gptel-org.el

If the source heading has any tag, the result of `org-get-heading` contains the tag string. By using `org-entry-get` to retrieve the `ITEM` property of the entry, you can get the true heading of the entry, which would be more suitable unless you want to include the tags in the topic.

Improve gptel-org-set-topic to not include tags in the default value

---

NEWS
gptel-gemini.el

This PR adds Gemini 2.5 Pro Preview (I/O edition): https://developers.googleblog.com/en/gemini-2-5-pro-io-improved-coding-performance/

Add `gemini-2.5-pro-preview-05-06` model to `gptel-gemini.el`

---

gptel-gh.el

The gpt-4.1 models appear to support media/"vision" when used via GitHub Copilot, and thus this PR aligns the capabilities of this model in `gptel--gh-models` to the capabilities of this model in `gptel--openai-models`.

gptel-gh: Add media capability to GitHub Copilot gpt-4.1 model

---

gptel-gh.el

gptel-gh: only sent vision-request header when there's media

---

NEWS
gptel-gemini.el

Gemini 2.5 Pro Preview 06-05: https://blog.google/products/gemini/gemini-2-5-pro-latest-preview/
This time they stated this is the last update of 2.5 Pro before GA...

Add `gemini-2.5-pro-preview-06-05` model to `gptel-gemini.el`

---

README.org
gptel.el

This pull request adds native support for [AI/ML API](https://aimlapi.com/app/), an OpenAI-compatible platform offering access to 300+ models including ChatGPT, Gemini, DeepSeek, and more — all with enterprise-grade reliability and rate limits.
* Added AI/ML API to the provider list in `README.org`
* Described setup instructions under a new `<details>` block
* Mentioned support in the `gptel.el` service comments
* Updated provider mentions in the supported model documentation section
From https://github.com/karthink/gptel/issues/907

feat: Added AI/ML API Integration

---

gptel-org.el

I thought it was saying the "current" headline but it actually finds whatever parent or grandparent headline that has the topic set.

gptel-org: Update gptel-org-set-topic docstring for clarity

---

gptel-transient.el

If using a list of symbols then the menu displays information about the info and debug functions, which have nothing to do with gptel's log level.

Fix log-level selection menu

---

gptel-gemini.el

Announcement: https://developers.googleblog.com/en/gemini-25-flash-lite-is-now-stable-and-generally-available/
Documentation: https://cloud.google.com/vertex-ai/generative-ai/docs/models/gemini/2-5-flash-lite
Also, remove duplicate definitions and correct the pricing of `gemini-2.5-flash-lite-preview-06-17` and `gemini-2.5-flash`, introduced in:
- https://github.com/karthink/gptel/pull/913
- https://github.com/karthink/gptel/pull/926

gptel-gemini: add `gemini-2.5-flash-lite` GA model

---

gptel-transient.el

If gptel--system-message and gptel directives are nil, we erroneously call (insert nil). We add "" to ensure non-nil is inserted into the buffer.
To currently reproduce the error; set `gptel--system-message` to nil, then attempt to call the manual edit system message option from the transient `gptel-menu`.
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
transient--exit-and-debug(error (wrong-type-argument char-or-string-p nil))
gptel--edit-directive(gptel--system-message :setup activate-mark)
#<subr gptel--suffix-system-message>(nil)
apply(#<subr gptel--suffix-system-message> nil)
#f(compiled-function (fn &rest args) (interactive nil) #<bytecode -0x1569efc26de924f3>)(#<subr gptel--suffix-system-message> nil)
funcall-interactively(#f(compiled-function …
```

Fix invalid type char-or-string-p when inserting nil for gptel--system-message

---

gptel-openai-extras.el

DeepSeek V3.1 has been released, introducing a bigger context window for all models and new costs. See
https://api-docs.deepseek.com/news/news250821.
* gptel-openai-extras.el (gptel-make-deepseek): Adjust `:context-window`, `:input-cost` and `:output-cost` to newly documented values.

gptel-openai: Update deepseek model specs

---

gptel-gh.el

Reuse properties defined in gptel-openai-extras but update context-window to 128, as returned by the Copilot Models API

gptel-gh: add grok-code-fast-1 model

---

NEWS
README.org
gptel-anthropic.el
gptel-bedrock.el
gptel-context.el
gptel-gemini.el
gptel-kagi.el
gptel-ollama.el
gptel-openai.el
gptel-request.el
gptel-transient.el
gptel.el

There are multiple-PRs that either duplicate each other or have merge-conflicts. 
This is a synthesis of all of these: #895 #925 #996 #1007 #983 
What does this do ?
- #925
Add profile-argument from; replace ```profile``` keyword with ```aws-profile```.
-  #895
Use :static argument for ```aws-profile``` for IAM cred.
- #996
Switch precedence; use aws-profile when provided.
- #1007 
Use ```AWS_BEARER_TOKEN_BEDROCK``` if provided at highest-precedence.
- #983 
Use ```aws-bearer-token``` if provided at highest-precedence.
If the authors of these PRs can test these out, we can push this in.
(@liangfu @leezu @lgfang @andykuszyk )

AWS bedrock-update

---

README.org

Corrected a typo in the reasoning content section.

Fix typo in reasoning content description
